assets/app/scripts/app.js, assets/app/styles/_nav.less, assets/app/views/_sidebar.html
=> Fix colors and further polish

assets/app/index.html, assets/app/styles/_label-selectize.less, assets/app/styles/main.less, assets/app/views/_project-nav.html, assets/bower.json
=> Filter selectize partials

assets/app/styles/_mixins.less, assets/app/styles/_sidebar.less, assets/app/styles/_variables.less
override patternfly sidebar-right bg color and tweak related element colors
=> Add word-break mixin

assets/app/scripts/directives/nav.js, assets/app/scripts/services/deployments.js, assets/app/views/browse/deployment.html, assets/app/views/browse/pod.html, assets/app/views/images.html, assets/app/views/services.html
=> Several fixes

assets/app/views/directives/_pod-metrics.html
Use the new class name for Patternfly v3.
@jwforres
=> Update Patternfly utilization chart class name

assets/app/styles/_core.less, assets/app/styles/_variables.less
=> Use @dl-horizontal-breakpoint

assets/app/scripts/controllers/modals/editModal.js, assets/app/views/modals/edit-resource.html
Replaces https://github.com/openshift/origin/pull/8157
=> Don't enable editor save button until after a change

assets/app/index.html, assets/app/scripts/app.js, assets/app/scripts/constants.js, assets/app/scripts/controllers/deployment.js, assets/app/scripts/controllers/deploymentConfig.js, assets/app/scripts/controllers/edit/autoscaler.js, assets/app/scripts/controllers/edit/healthChecks.js, assets/app/scripts/controllers/setLimits.js, assets/app/scripts/directives/editCommand.js, assets/app/scripts/directives/editProbe.js, assets/app/scripts/directives/resources.js, assets/app/scripts/directives/util.js, assets/app/scripts/filters/resources.js, assets/app/scripts/services/navigate.js, assets/app/styles/_core.less, assets/app/views/_pod-template.html, assets/app/views/browse/_deployment-details.html, assets/app/views/browse/deployment-config.html, assets/app/views/browse/deployment.html, assets/app/views/browse/replication-controller.html, assets/app/views/directives/_edit-command.html, assets/app/views/directives/_edit-probe.html, assets/app/views/directives/_probe.html, assets/app/views/directives/osc-key-values.html, assets/app/views/edit/health-checks.html, assets/app/views/set-limits.html, assets/bower.json, assets/extensions/examples/online-extensions.js
https://trello.com/c/OWOhA8fv
Replaces https://github.com/openshift/origin/pull/7312, rebased for 1.3.
TODO:
=> Web console support for health checks

assets/app/styles/_core.less
=> Left align tabs when they wrap to second line

assets/Gruntfile.js, assets/app/index.html
Fixes a minification problem in the 1.3 branch.
=> Exclude google-code-prettify

assets/app/views/directives/_probe.html
https://bugzilla.redhat.com/show_bug.cgi?id=1326189
@jwforres PTAL. This is the only place we had this typo.
=> Fix httpGet path in pod template

assets/app/scripts/services/metrics.js
Fixes https://github.com/openshift/origin/issues/8470.
cc @spadgett
=> Fix usage rate calculation for network metrics in pod page

assets/app/scripts/directives/metrics.js, assets/app/scripts/services/metrics.js
https://bugzilla.redhat.com/show_bug.cgi?id=1326262
* Calculate rate from point.max - point.min
* Make smallest time range one hour
* Use 2 decimal points precision for y-axis ticks
* Refresh every 15s (from 30s)
@jwforres @fabianofranz
=> Metrics updates

assets/app/scripts/directives/editCommand.js, assets/app/scripts/filters/strings.js, assets/app/styles/_core.less, assets/app/views/directives/_edit-command.html, assets/app/views/directives/_probe.html, assets/app/views/modals/debug-terminal.html
=> Handle multiline command arguments in web console

assets/app/scripts/directives/deleteLink.js, assets/app/scripts/filters/resources.js, assets/app/views/directives/events.html, assets/app/views/directives/hpa.html, assets/app/views/modals/edit-resource.html
=> Update humanizeKind filter to use lowercase by default

assets/app/scripts/directives/deleteLink.js, assets/app/views/modals/delete-resource.html, assets/app/views/projects.html, assets/app/views/settings.html
@jwforres opinion on this change?
=> Confirm project delete by typing project name

assets/app/index.html, assets/app/scripts/app.js, assets/app/scripts/controllers/create/createFromImage.js, assets/app/scripts/controllers/createRoute.js, assets/app/scripts/controllers/edit/route.js, assets/app/scripts/directives/oscFileInput.js, assets/app/scripts/directives/oscRouting.js, assets/app/scripts/directives/popups.js, assets/app/scripts/filters/resources.js, assets/app/scripts/services/applicationGenerator.js, assets/app/scripts/services/routes.js, assets/app/styles/_core.less, assets/app/views/browse/route.html, assets/app/views/create-route.html, assets/app/views/directives/osc-file-input.html, assets/app/views/directives/osc-routing.html, assets/app/views/edit/route.html
=> Edit routes in web console

assets/app/scripts/directives/util.js, assets/app/styles/_core.less, assets/app/views/browse/build-config.html, assets/app/views/browse/deployment-config.html, assets/app/views/directives/_copy-to-clipboard.html, assets/app/views/modals/debug-terminal.html
=> Changing copy to clipboard button to an input + button

assets/app/index.html, assets/app/scripts/app.js, assets/app/scripts/constants.js, assets/app/scripts/controllers/otherResources.js, assets/app/scripts/directives/deleteLink.js, assets/app/scripts/directives/editLink.js, assets/app/scripts/directives/labels.js, assets/app/scripts/filters/resources.js, assets/app/scripts/services/api.js, assets/app/styles/_core.less, assets/app/styles/_tables.less, assets/app/views/other-resources.html, assets/app/views/services.html, assets/bower.json
Builds off the api discovery branch
=> Other resources page

assets/app/scripts/controllers/edit/buildConfig.js, assets/app/views/edit/build-config.html
@jwforres PTAL
fixes https://github.com/openshift/origin/issues/8536
=> Enabling WebHooks from console will add Generic webhook

assets/app/index.html, assets/app/scripts/controllers/edit/buildConfig.js, assets/app/scripts/filters/resources.js, assets/app/styles/_core.less, assets/app/views/browse/build-config.html, assets/app/views/edit/build-config.html, assets/bower.json
https://trello.com/c/KMyd8ETi
Based on https://github.com/openshift/origin/pull/7949
View Jenkins Pipeline build:
Edit Jenkins Pipeline build:
/cc @jwforres @bparees
=> Web console support for  JenkinsPipeline builds

assets/app/scripts/controllers/createProject.js, assets/app/views/create-project.html
Fixes #4169
Many thanks to @benjaminapetersen for the excellent instruction and assistance.
=> Changing notifications to alerts

assets/app/views/_edit-request-limit.html
https://bugzilla.redhat.com/show_bug.cgi?id=1312416
=> Don't validate limit against request limit range default
